{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "collapsed": true,
     "inputWidgets": {},
     "nuid": "f1fc78c2-7c9c-4710-aa11-abb2b064f1fa",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Python interpreter will be restarted.\nCollecting yfinance\n  Downloading yfinance-0.2.52-py2.py3-none-any.whl (108 kB)\nRequirement already satisfied: pandas>=1.3.0 in /databricks/python3/lib/python3.9/site-packages (from yfinance) (1.4.2)\nRequirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from yfinance) (2.6.2)\nCollecting lxml>=4.9.1\n  Downloading lxml-5.3.1-cp39-cp39-manylinux_2_28_x86_64.whl (5.2 MB)\nCollecting requests>=2.31\n  Downloading requests-2.32.3-py3-none-any.whl (64 kB)\nCollecting multitasking>=0.0.7\n  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)\nCollecting pytz>=2022.5\n  Downloading pytz-2025.1-py2.py3-none-any.whl (507 kB)\nCollecting frozendict>=2.3.4\n  Downloading frozendict-2.4.6-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (116 kB)\nRequirement already satisfied: beautifulsoup4>=4.11.1 in /databricks/python3/lib/python3.9/site-packages (from yfinance) (4.11.1)\nCollecting html5lib>=1.1\n  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)\nCollecting peewee>=3.16.2\n  Downloading peewee-3.17.9.tar.gz (3.0 MB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'error'\n  ERROR: Command errored out with exit status 1:\n   command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp4i0vlxdq\n       cwd: /tmp/pip-install-6qw80skr/peewee_c5619674c7c04416be1201a3e6c5ca15\n  Complete output (38 lines):\n  \n  Error compiling Cython file:\n  ------------------------------------------------------------\n  ...\n  \n  \n  # We define an xConnect function, but leave xCreate NULL so that the\n  # table-function can be called eponymously.\n  cdef int pwConnect(sqlite3 *db, void *pAux, int argc, const char *const*argv,\n                     sqlite3_vtab **ppVtab, char **pzErr) noexcept with gil:\n                                                         ^\n  ------------------------------------------------------------\n  \n  playhouse/_sqlite_ext.pyx:389:56: Syntax error in C variable declaration\n  Compiling playhouse/_sqlite_ext.pyx because it depends on /databricks/python/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.\n  [1/1] Cythonizing playhouse/_sqlite_ext.pyx\n  Traceback (most recent call last):\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n      main()\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n      json_out['return_val'] = hook(**hook_input['kwargs'])\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n      return hook(config_settings)\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 177, in get_requires_for_build_wheel\n      return self._get_build_requires(\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 159, in _get_build_requires\n      self.run_setup()\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 174, in run_setup\n      exec(compile(code, __file__, 'exec'), locals())\n    File \"setup.py\", line 201, in <module>\n      _do_setup(extension_support, sqlite_extension_support)\n    File \"setup.py\", line 196, in _do_setup\n      ext_modules=cythonize(ext_modules))\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1127, in cythonize\n      cythonize_one(*args)\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1250, in cythonize_one\n      raise CompileError(None, pyx_file)\n  Cython.Compiler.Errors.CompileError: playhouse/_sqlite_ext.pyx\n  ----------------------------------------\nWARNING: Discarding https://files.pythonhosted.org/packages/57/09/4393bd378e70b7fc3163ee83353cc27bb520010a5c2b3c924121e7e7e068/peewee-3.17.9.tar.gz#sha256=fe15cd001758e324c8e3ca8c8ed900e7397c2907291789e1efc383e66b9bc7a8 (from https://pypi.org/simple/peewee/). Command errored out with exit status 1: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp4i0vlxdq Check the logs for full command output.\n  Downloading peewee-3.17.8.tar.gz (948 kB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'error'\n  ERROR: Command errored out with exit status 1:\n   command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp3y1sxopi\n       cwd: /tmp/pip-install-6qw80skr/peewee_2dfc05d3b59c443a95700a3a30fa9b18\n  Complete output (38 lines):\n  \n  Error compiling Cython file:\n  ------------------------------------------------------------\n  ...\n  \n  \n  # We define an xConnect function, but leave xCreate NULL so that the\n  # table-function can be called eponymously.\n  cdef int pwConnect(sqlite3 *db, void *pAux, int argc, const char *const*argv,\n                     sqlite3_vtab **ppVtab, char **pzErr) noexcept with gil:\n                                                         ^\n  ------------------------------------------------------------\n  \n  playhouse/_sqlite_ext.pyx:389:56: Syntax error in C variable declaration\n  Compiling playhouse/_sqlite_ext.pyx because it depends on /databricks/python/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.\n  [1/1] Cythonizing playhouse/_sqlite_ext.pyx\n  Traceback (most recent call last):\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n      main()\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n      json_out['return_val'] = hook(**hook_input['kwargs'])\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n      return hook(config_settings)\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 177, in get_requires_for_build_wheel\n      return self._get_build_requires(\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 159, in _get_build_requires\n      self.run_setup()\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 174, in run_setup\n      exec(compile(code, __file__, 'exec'), locals())\n    File \"setup.py\", line 201, in <module>\n      _do_setup(extension_support, sqlite_extension_support)\n    File \"setup.py\", line 196, in _do_setup\n      ext_modules=cythonize(ext_modules))\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1127, in cythonize\n      cythonize_one(*args)\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1250, in cythonize_one\n      raise CompileError(None, pyx_file)\n  Cython.Compiler.Errors.CompileError: playhouse/_sqlite_ext.pyx\n  ----------------------------------------\nWARNING: Discarding https://files.pythonhosted.org/packages/b4/dc/832bcf4ea5ee2ebc4ea42ef36e44a451de5d80f8b9858bf2066e30738c67/peewee-3.17.8.tar.gz#sha256=ce1d05db3438830b989a1b9d0d0aa4e7f6134d5f6fd57686eeaa26a3e6485a8c (from https://pypi.org/simple/peewee/). Command errored out with exit status 1: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp3y1sxopi Check the logs for full command output.\n  Downloading peewee-3.17.7.tar.gz (939 kB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'error'\n  ERROR: Command errored out with exit status 1:\n   command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpl2nhih13\n       cwd: /tmp/pip-install-6qw80skr/peewee_44a63ffcddef4bd88cccc359b1e233d3\n  Complete output (38 lines):\n  \n  Error compiling Cython file:\n  ------------------------------------------------------------\n  ...\n  \n  \n  # We define an xConnect function, but leave xCreate NULL so that the\n  # table-function can be called eponymously.\n  cdef int pwConnect(sqlite3 *db, void *pAux, int argc, const char *const*argv,\n                     sqlite3_vtab **ppVtab, char **pzErr) noexcept with gil:\n                                                         ^\n  ------------------------------------------------------------\n  \n  playhouse/_sqlite_ext.pyx:389:56: Syntax error in C variable declaration\n  Compiling playhouse/_sqlite_ext.pyx because it depends on /databricks/python/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.\n  [1/1] Cythonizing playhouse/_sqlite_ext.pyx\n  Traceback (most recent call last):\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n      main()\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n      json_out['return_val'] = hook(**hook_input['kwargs'])\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n      return hook(config_settings)\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 177, in get_requires_for_build_wheel\n      return self._get_build_requires(\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 159, in _get_build_requires\n      self.run_setup()\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 174, in run_setup\n      exec(compile(code, __file__, 'exec'), locals())\n    File \"setup.py\", line 201, in <module>\n      _do_setup(extension_support, sqlite_extension_support)\n    File \"setup.py\", line 196, in _do_setup\n      ext_modules=cythonize(ext_modules))\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1127, in cythonize\n      cythonize_one(*args)\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1250, in cythonize_one\n      raise CompileError(None, pyx_file)\n  Cython.Compiler.Errors.CompileError: playhouse/_sqlite_ext.pyx\n  ----------------------------------------\nWARNING: Discarding https://files.pythonhosted.org/packages/e1/2d/c5e34703c118da6dae4de89d5c9b5a2fb9fbc2f7789ac2c8d8836f6367ba/peewee-3.17.7.tar.gz#sha256=6aefc700bd530fc6ac23fa19c9c5b47041751d92985b799169c8e318e97eabaa (from https://pypi.org/simple/peewee/). Command errored out with exit status 1: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpl2nhih13 Check the logs for full command output.\n  Downloading peewee-3.17.6.tar.gz (3.0 MB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'error'\n  ERROR: Command errored out with exit status 1:\n   command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpp4vmwmph\n       cwd: /tmp/pip-install-6qw80skr/peewee_714fb0d1e84d42f689009105715e568c\n  Complete output (38 lines):\n  \n  Error compiling Cython file:\n  ------------------------------------------------------------\n  ...\n  \n  \n  # We define an xConnect function, but leave xCreate NULL so that the\n  # table-function can be called eponymously.\n  cdef int pwConnect(sqlite3 *db, void *pAux, int argc, const char *const*argv,\n                     sqlite3_vtab **ppVtab, char **pzErr) noexcept with gil:\n                                                         ^\n  ------------------------------------------------------------\n  \n  playhouse/_sqlite_ext.pyx:389:56: Syntax error in C variable declaration\n  Compiling playhouse/_sqlite_ext.pyx because it depends on /databricks/python/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.\n  [1/1] Cythonizing playhouse/_sqlite_ext.pyx\n  Traceback (most recent call last):\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n      main()\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n      json_out['return_val'] = hook(**hook_input['kwargs'])\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n      return hook(config_settings)\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 177, in get_requires_for_build_wheel\n      return self._get_build_requires(\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 159, in _get_build_requires\n      self.run_setup()\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 174, in run_setup\n      exec(compile(code, __file__, 'exec'), locals())\n    File \"setup.py\", line 201, in <module>\n      _do_setup(extension_support, sqlite_extension_support)\n    File \"setup.py\", line 196, in _do_setup\n      ext_modules=cythonize(ext_modules))\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1127, in cythonize\n      cythonize_one(*args)\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1250, in cythonize_one\n      raise CompileError(None, pyx_file)\n  Cython.Compiler.Errors.CompileError: playhouse/_sqlite_ext.pyx\n  ----------------------------------------\nWARNING: Discarding https://files.pythonhosted.org/packages/bd/be/e9c886b4601a19f4c34a1b75c5fe8b98a2115dd964251a76b24c977c369d/peewee-3.17.6.tar.gz#sha256=cea5592c6f4da1592b7cff8eaf655be6648a1f5857469e30037bf920c03fb8fb (from https://pypi.org/simple/peewee/). Command errored out with exit status 1: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpp4vmwmph Check the logs for full command output.\n  Downloading peewee-3.17.5.tar.gz (3.0 MB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'error'\n  ERROR: Command errored out with exit status 1:\n   command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpwjmtno6x\n       cwd: /tmp/pip-install-6qw80skr/peewee_a125df7690fd411e92d2cf310b8c16fd\n  Complete output (38 lines):\n  \n  Error compiling Cython file:\n  ------------------------------------------------------------\n  ...\n  \n  \n  # We define an xConnect function, but leave xCreate NULL so that the\n  # table-function can be called eponymously.\n  cdef int pwConnect(sqlite3 *db, void *pAux, int argc, const char *const*argv,\n                     sqlite3_vtab **ppVtab, char **pzErr) noexcept with gil:\n                                                         ^\n  ------------------------------------------------------------\n  \n  playhouse/_sqlite_ext.pyx:389:56: Syntax error in C variable declaration\n  Compiling playhouse/_sqlite_ext.pyx because it depends on /databricks/python/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.\n  [1/1] Cythonizing playhouse/_sqlite_ext.pyx\n  Traceback (most recent call last):\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n      main()\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n      json_out['return_val'] = hook(**hook_input['kwargs'])\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n      return hook(config_settings)\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 177, in get_requires_for_build_wheel\n      return self._get_build_requires(\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 159, in _get_build_requires\n      self.run_setup()\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 174, in run_setup\n      exec(compile(code, __file__, 'exec'), locals())\n    File \"setup.py\", line 201, in <module>\n      _do_setup(extension_support, sqlite_extension_support)\n    File \"setup.py\", line 196, in _do_setup\n      ext_modules=cythonize(ext_modules))\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1127, in cythonize\n      cythonize_one(*args)\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1250, in cythonize_one\n      raise CompileError(None, pyx_file)\n  Cython.Compiler.Errors.CompileError: playhouse/_sqlite_ext.pyx\n  ----------------------------------------\nWARNING: Discarding https://files.pythonhosted.org/packages/1e/d4/22c2909b5a0b36e69471e699d673c2985f7691ca29870798a29e0a3d0e2b/peewee-3.17.5.tar.gz#sha256=e1b6a64192207fd3ddb4e1188054820f42aef0aadfa749e3981af3c119a76420 (from https://pypi.org/simple/peewee/). Command errored out with exit status 1: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpwjmtno6x Check the logs for full command output.\n  Downloading peewee-3.17.3.tar.gz (3.0 MB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'error'\n  ERROR: Command errored out with exit status 1:\n   command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpkzjevpvi\n       cwd: /tmp/pip-install-6qw80skr/peewee_0224c4c49e944fd9b217c999505afa8f\n  Complete output (40 lines):\n  \n  Error compiling Cython file:\n  ------------------------------------------------------------\n  ...\n  \n  \n  # We define an xConnect function, but leave xCreate NULL so that the\n  # table-function can be called eponymously.\n  cdef int pwConnect(sqlite3 *db, void *pAux, int argc, const char *const*argv,\n                     sqlite3_vtab **ppVtab, char **pzErr) noexcept with gil:\n                                                         ^\n  ------------------------------------------------------------\n  \n  playhouse/_sqlite_ext.pyx:389:56: Syntax error in C variable declaration\n  Compiling playhouse/_sqlite_ext.pyx because it depends on /databricks/python/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.\n  [1/1] Cythonizing playhouse/_sqlite_ext.pyx\n  Traceback (most recent call last):\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n      main()\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n      json_out['return_val'] = hook(**hook_input['kwargs'])\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n      return hook(config_settings)\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 177, in get_requires_for_build_wheel\n      return self._get_build_requires(\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 159, in _get_build_requires\n      self.run_setup()\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 281, in run_setup\n      super(_BuildMetaLegacyBackend,\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 174, in run_setup\n      exec(compile(code, __file__, 'exec'), locals())\n    File \"setup.py\", line 196, in <module>\n      _do_setup(extension_support, sqlite_extension_support)\n    File \"setup.py\", line 191, in _do_setup\n      ext_modules=cythonize(ext_modules))\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1127, in cythonize\n      cythonize_one(*args)\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1250, in cythonize_one\n      raise CompileError(None, pyx_file)\n  Cython.Compiler.Errors.CompileError: playhouse/_sqlite_ext.pyx\n  ----------------------------------------\nWARNING: Discarding https://files.pythonhosted.org/packages/7a/b1/2331e6b1fc8c61686dd9276f34142265462640eb0dd431246e30c4461065/peewee-3.17.3.tar.gz#sha256=ef15f90b628e41a584be8306cdc3243c51f73ce88b06154d9572f6d0284a0169 (from https://pypi.org/simple/peewee/). Command errored out with exit status 1: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpkzjevpvi Check the logs for full command output.\n  Downloading peewee-3.17.2.tar.gz (938 kB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'error'\n  ERROR: Command errored out with exit status 1:\n   command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpz_mkqhv5\n       cwd: /tmp/pip-install-6qw80skr/peewee_03c2545080874c30b887f6e1c4792e96\n  Complete output (40 lines):\n  \n  Error compiling Cython file:\n  ------------------------------------------------------------\n  ...\n  \n  \n  # We define an xConnect function, but leave xCreate NULL so that the\n  # table-function can be called eponymously.\n  cdef int pwConnect(sqlite3 *db, void *pAux, int argc, const char *const*argv,\n                     sqlite3_vtab **ppVtab, char **pzErr) noexcept with gil:\n                                                         ^\n  ------------------------------------------------------------\n  \n  playhouse/_sqlite_ext.pyx:389:56: Syntax error in C variable declaration\n  Compiling playhouse/_sqlite_ext.pyx because it depends on /databricks/python/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.\n  [1/1] Cythonizing playhouse/_sqlite_ext.pyx\n  Traceback (most recent call last):\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n      main()\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n      json_out['return_val'] = hook(**hook_input['kwargs'])\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n      return hook(config_settings)\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 177, in get_requires_for_build_wheel\n      return self._get_build_requires(\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 159, in _get_build_requires\n      self.run_setup()\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 281, in run_setup\n      super(_BuildMetaLegacyBackend,\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 174, in run_setup\n      exec(compile(code, __file__, 'exec'), locals())\n    File \"setup.py\", line 196, in <module>\n      _do_setup(extension_support, sqlite_extension_support)\n    File \"setup.py\", line 191, in _do_setup\n      ext_modules=cythonize(ext_modules))\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1127, in cythonize\n      cythonize_one(*args)\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1250, in cythonize_one\n      raise CompileError(None, pyx_file)\n  Cython.Compiler.Errors.CompileError: playhouse/_sqlite_ext.pyx\n  ----------------------------------------\nWARNING: Discarding https://files.pythonhosted.org/packages/35/6d/54848039cd02f4aca217855570e8300a64d933f9791443aa3d7c02ecc901/peewee-3.17.2.tar.gz#sha256=2fe35224317d6b50e162ac44880a0d281d4ac0d53c7ae9d228eb769299618fb1 (from https://pypi.org/simple/peewee/). Command errored out with exit status 1: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpz_mkqhv5 Check the logs for full command output.\n  Downloading peewee-3.17.1.tar.gz (3.0 MB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'error'\n  ERROR: Command errored out with exit status 1:\n   command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmptki3anzz\n       cwd: /tmp/pip-install-6qw80skr/peewee_de686486d78e46db9425db259a830691\n  Complete output (40 lines):\n  \n  Error compiling Cython file:\n  ------------------------------------------------------------\n  ...\n  \n  \n  # We define an xConnect function, but leave xCreate NULL so that the\n  # table-function can be called eponymously.\n  cdef int pwConnect(sqlite3 *db, void *pAux, int argc, const char *const*argv,\n                     sqlite3_vtab **ppVtab, char **pzErr) noexcept with gil:\n                                                         ^\n  ------------------------------------------------------------\n  \n  playhouse/_sqlite_ext.pyx:389:56: Syntax error in C variable declaration\n  Compiling playhouse/_sqlite_ext.pyx because it depends on /databricks/python/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.\n  [1/1] Cythonizing playhouse/_sqlite_ext.pyx\n  Traceback (most recent call last):\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n      main()\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n      json_out['return_val'] = hook(**hook_input['kwargs'])\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n      return hook(config_settings)\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 177, in get_requires_for_build_wheel\n      return self._get_build_requires(\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 159, in _get_build_requires\n      self.run_setup()\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 281, in run_setup\n      super(_BuildMetaLegacyBackend,\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 174, in run_setup\n      exec(compile(code, __file__, 'exec'), locals())\n    File \"setup.py\", line 196, in <module>\n      _do_setup(extension_support, sqlite_extension_support)\n    File \"setup.py\", line 191, in _do_setup\n      ext_modules=cythonize(ext_modules))\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1127, in cythonize\n      cythonize_one(*args)\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1250, in cythonize_one\n      raise CompileError(None, pyx_file)\n  Cython.Compiler.Errors.CompileError: playhouse/_sqlite_ext.pyx\n  ----------------------------------------\nWARNING: Discarding https://files.pythonhosted.org/packages/8d/a5/89cdbc4a7f6d7a0624c120be102db770ee717aa371066581e3daf2beb96f/peewee-3.17.1.tar.gz#sha256=e009ac4227c4fdc0058a56e822ad5987684f0a1fbb20fed577200785102581c3 (from https://pypi.org/simple/peewee/). Command errored out with exit status 1: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmptki3anzz Check the logs for full command output.\n  Downloading peewee-3.17.0.tar.gz (2.9 MB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'error'\n  ERROR: Command errored out with exit status 1:\n   command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpt56phr_w\n       cwd: /tmp/pip-install-6qw80skr/peewee_312d28bced2045e09c4fa90d54ac22bb\n  Complete output (40 lines):\n  \n  Error compiling Cython file:\n  ------------------------------------------------------------\n  ...\n  \n  \n  # We define an xConnect function, but leave xCreate NULL so that the\n  # table-function can be called eponymously.\n  cdef int pwConnect(sqlite3 *db, void *pAux, int argc, const char *const*argv,\n                     sqlite3_vtab **ppVtab, char **pzErr) noexcept with gil:\n                                                         ^\n  ------------------------------------------------------------\n  \n  playhouse/_sqlite_ext.pyx:389:56: Syntax error in C variable declaration\n  Compiling playhouse/_sqlite_ext.pyx because it depends on /databricks/python/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.\n  [1/1] Cythonizing playhouse/_sqlite_ext.pyx\n  Traceback (most recent call last):\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n      main()\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n      json_out['return_val'] = hook(**hook_input['kwargs'])\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n      return hook(config_settings)\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 177, in get_requires_for_build_wheel\n      return self._get_build_requires(\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 159, in _get_build_requires\n      self.run_setup()\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 281, in run_setup\n      super(_BuildMetaLegacyBackend,\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 174, in run_setup\n      exec(compile(code, __file__, 'exec'), locals())\n    File \"setup.py\", line 196, in <module>\n      _do_setup(extension_support, sqlite_extension_support)\n    File \"setup.py\", line 191, in _do_setup\n      ext_modules=cythonize(ext_modules))\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1127, in cythonize\n      cythonize_one(*args)\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1250, in cythonize_one\n      raise CompileError(None, pyx_file)\n  Cython.Compiler.Errors.CompileError: playhouse/_sqlite_ext.pyx\n  ----------------------------------------\nWARNING: Discarding https://files.pythonhosted.org/packages/6a/30/a727bb1420076b3c14b60911d111f0fc0449d31a1123a1ad18878a7a4e40/peewee-3.17.0.tar.gz#sha256=3a56967f28a43ca7a4287f4803752aeeb1a57a08dee2e839b99868181dfb5df8 (from https://pypi.org/simple/peewee/). Command errored out with exit status 1: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpt56phr_w Check the logs for full command output.\n  Downloading peewee-3.16.3.tar.gz (928 kB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'error'\n  ERROR: Command errored out with exit status 1:\n   command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpqyy2bq6_\n       cwd: /tmp/pip-install-6qw80skr/peewee_dc51bc46d8774917bccc08c98fa5228a\n  Complete output (40 lines):\n  \n  Error compiling Cython file:\n  ------------------------------------------------------------\n  ...\n  \n  \n  # We define an xConnect function, but leave xCreate NULL so that the\n  # table-function can be called eponymously.\n  cdef int pwConnect(sqlite3 *db, void *pAux, int argc, const char *const*argv,\n                     sqlite3_vtab **ppVtab, char **pzErr) noexcept with gil:\n                                                         ^\n  ------------------------------------------------------------\n  \n  playhouse/_sqlite_ext.pyx:389:56: Syntax error in C variable declaration\n  Compiling playhouse/_sqlite_ext.pyx because it depends on /databricks/python/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.\n  [1/1] Cythonizing playhouse/_sqlite_ext.pyx\n  Traceback (most recent call last):\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n      main()\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n      json_out['return_val'] = hook(**hook_input['kwargs'])\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n      return hook(config_settings)\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 177, in get_requires_for_build_wheel\n      return self._get_build_requires(\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 159, in _get_build_requires\n      self.run_setup()\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 281, in run_setup\n      super(_BuildMetaLegacyBackend,\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 174, in run_setup\n      exec(compile(code, __file__, 'exec'), locals())\n    File \"setup.py\", line 196, in <module>\n      _do_setup(extension_support, sqlite_extension_support)\n    File \"setup.py\", line 191, in _do_setup\n      ext_modules=cythonize(ext_modules))\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1127, in cythonize\n      cythonize_one(*args)\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1250, in cythonize_one\n      raise CompileError(None, pyx_file)\n  Cython.Compiler.Errors.CompileError: playhouse/_sqlite_ext.pyx\n  ----------------------------------------\nWARNING: Discarding https://files.pythonhosted.org/packages/e2/1e/6455dc3c759af3e565414985c5c6f845d3e5f83bbf4a24cdd0aef9cc3f83/peewee-3.16.3.tar.gz#sha256=12b30e931193bc37b11f7c2ac646e3f67125a8b1a543ad6ab37ad124c8df7d16 (from https://pypi.org/simple/peewee/). Command errored out with exit status 1: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpqyy2bq6_ Check the logs for full command output.\n  Downloading peewee-3.16.2.tar.gz (2.9 MB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'error'\n  ERROR: Command errored out with exit status 1:\n   command: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpviwh2uqg\n       cwd: /tmp/pip-install-6qw80skr/peewee_a30d658a7a5f44b5b32e640e230b369d\n  Complete output (40 lines):\n  \n  Error compiling Cython file:\n  ------------------------------------------------------------\n  ...\n      def autocommit(self):\n          if self.conn.initialized and self.conn.db:\n              return sqlite3_get_autocommit(self.conn.db) != 0\n  \n  \n  cdef int _commit_callback(void *userData) noexcept with gil:\n                                           ^\n  ------------------------------------------------------------\n  \n  playhouse/_sqlite_ext.pyx:1511:42: Syntax error in C variable declaration\n  Compiling playhouse/_sqlite_ext.pyx because it depends on /databricks/python/lib/python3.9/site-packages/Cython/Includes/libc/string.pxd.\n  [1/1] Cythonizing playhouse/_sqlite_ext.pyx\n  Traceback (most recent call last):\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n      main()\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n      json_out['return_val'] = hook(**hook_input['kwargs'])\n    File \"/local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n      return hook(config_settings)\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 177, in get_requires_for_build_wheel\n      return self._get_build_requires(\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 159, in _get_build_requires\n      self.run_setup()\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 281, in run_setup\n      super(_BuildMetaLegacyBackend,\n    File \"/databricks/python/lib/python3.9/site-packages/setuptools/build_meta.py\", line 174, in run_setup\n      exec(compile(code, __file__, 'exec'), locals())\n    File \"setup.py\", line 196, in <module>\n      _do_setup(extension_support, sqlite_extension_support)\n    File \"setup.py\", line 191, in _do_setup\n      ext_modules=cythonize(ext_modules))\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1127, in cythonize\n      cythonize_one(*args)\n    File \"/databricks/python/lib/python3.9/site-packages/Cython/Build/Dependencies.py\", line 1250, in cythonize_one\n      raise CompileError(None, pyx_file)\n  Cython.Compiler.Errors.CompileError: playhouse/_sqlite_ext.pyx\n  ----------------------------------------\nWARNING: Discarding https://files.pythonhosted.org/packages/a9/50/1dd5ea74c559df4afb8391f8d05f0fec685dbe8effba13bb9072901eb288/peewee-3.16.2.tar.gz#sha256=10769981198c7311f84a0ca8db892fa213303a8eb1305deb795a71e7bd606a91 (from https://pypi.org/simple/peewee/). Command errored out with exit status 1: /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/bin/python /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpviwh2uqg Check the logs for full command output.\nCollecting yfinance\n  Downloading yfinance-0.2.51-py2.py3-none-any.whl (104 kB)\n  Downloading yfinance-0.2.50-py2.py3-none-any.whl (102 kB)\n  Downloading yfinance-0.2.49-py2.py3-none-any.whl (101 kB)\n  Downloading yfinance-0.2.48-py2.py3-none-any.whl (101 kB)\n  Downloading yfinance-0.2.47-py2.py3-none-any.whl (101 kB)\n  Downloading yfinance-0.2.46-py2.py3-none-any.whl (100 kB)\n  Downloading yfinance-0.2.45-py2.py3-none-any.whl (100 kB)\n  Downloading yfinance-0.2.44-py2.py3-none-any.whl (94 kB)\n  Downloading yfinance-0.2.43-py2.py3-none-any.whl (84 kB)\n  Downloading yfinance-0.2.42-py2.py3-none-any.whl (84 kB)\n  Downloading yfinance-0.2.41-py2.py3-none-any.whl (73 kB)\n  Downloading yfinance-0.2.40-py2.py3-none-any.whl (73 kB)\n  Downloading yfinance-0.2.39-py2.py3-none-any.whl (73 kB)\n  Downloading yfinance-0.2.38-py2.py3-none-any.whl (72 kB)\nCollecting appdirs>=1.4.4\n  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)\nCollecting yfinance\n  Downloading yfinance-0.2.37-py2.py3-none-any.whl (72 kB)\n  Downloading yfinance-0.2.36-py2.py3-none-any.whl (72 kB)\n  Downloading yfinance-0.2.35-py2.py3-none-any.whl (72 kB)\n  Downloading yfinance-0.2.34-py2.py3-none-any.whl (72 kB)\n  Downloading yfinance-0.2.33-py2.py3-none-any.whl (69 kB)\n  Downloading yfinance-0.2.32-py2.py3-none-any.whl (68 kB)\n  Downloading yfinance-0.2.31-py2.py3-none-any.whl (65 kB)\n  Downloading yfinance-0.2.30-py2.py3-none-any.whl (65 kB)\n  Downloading yfinance-0.2.29-py2.py3-none-any.whl (65 kB)\n  Downloading yfinance-0.2.28-py2.py3-none-any.whl (65 kB)\nRequirement already satisfied: numpy>=1.16.5 in /databricks/python3/lib/python3.9/site-packages (from yfinance) (1.21.5)\nRequirement already satisfied: soupsieve>1.2 in /databricks/python3/lib/python3.9/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.1)\nRequirement already satisfied: six>=1.9 in /databricks/python3/lib/python3.9/site-packages (from html5lib>=1.1->yfinance) (1.16.0)\nRequirement already satisfied: webencodings in /databricks/python3/lib/python3.9/site-packages (from html5lib>=1.1->yfinance) (0.5.1)\nRequirement already satisfied: python-dateutil>=2.8.1 in /databricks/python3/lib/python3.9/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)\nRequirement already satisfied: urllib3<3,>=1.21.1 in /databricks/python3/lib/python3.9/site-packages (from requests>=2.31->yfinance) (1.26.9)\nRequirement already satisfied: certifi>=2017.4.17 in /databricks/python3/lib/python3.9/site-packages (from requests>=2.31->yfinance) (2021.10.8)\nRequirement already satisfied: idna<4,>=2.5 in /databricks/python3/lib/python3.9/site-packages (from requests>=2.31->yfinance) (3.3)\nRequirement already satisfied: charset-normalizer<4,>=2 in /databricks/python3/lib/python3.9/site-packages (from requests>=2.31->yfinance) (2.0.4)\nInstalling collected packages: pytz, requests, multitasking, lxml, html5lib, frozendict, appdirs, yfinance\n  Attempting uninstall: pytz\n    Found existing installation: pytz 2021.3\n    Not uninstalling pytz at /databricks/python3/lib/python3.9/site-packages, outside environment /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9\n    Can't uninstall 'pytz'. No files were found to uninstall.\n  Attempting uninstall: requests\n    Found existing installation: requests 2.27.1\n    Not uninstalling requests at /databricks/python3/lib/python3.9/site-packages, outside environment /local_disk0/.ephemeral_nfs/envs/pythonEnv-643326ca-8d6f-429d-af89-0881388d04c9\n    Can't uninstall 'requests'. No files were found to uninstall.\nSuccessfully installed appdirs-1.4.4 frozendict-2.4.6 html5lib-1.1 lxml-5.3.1 multitasking-0.0.11 pytz-2025.1 requests-2.32.3 yfinance-0.2.28\nPython interpreter will be restarted.\n"
     ]
    }
   ],
   "source": [
    "pip install yfinance"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "19696471-4daf-458d-a83e-787dea2289dd",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "display_data",
     "data": {
      "application/vnd.databricks.v1+bamboolib_hint": "{\"pd.DataFrames\": [], \"version\": \"0.0.1\"}",
      "text/plain": []
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import yfinance          as yf\n",
    "import pandas            as pd\n",
    "import numpy             as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "from scipy.stats import norm\n",
    "\n",
    "import datetime"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 2048000,
      "rowLimit": 10000
     },
     "inputWidgets": {},
     "nuid": "c0a4eaba-8444-4534-a5ce-3a3df25f218f",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\r[*********************100%%**********************]  1 of 1 completed\n\r[*********************100%%**********************]  1 of 1 completed\n\r[*********************100%%**********************]  1 of 1 completed\n\r[*********************100%%**********************]  1 of 1 completed\n\r[*********************100%%**********************]  1 of 1 completed\n\r[*********************100%%**********************]  1 of 1 completed\nCâmbio médio USD/BRL em Marco 2024: 4.976608934856596\nCâmbio médio EUR/BRL em Marco 2024: 5.400209494999477\nCâmbio médio USD/BRL em Novembro 2024: 5.783444086710612\nCâmbio médio EUR/BRL em Novembro 2024: 6.146246478671119\nCâmbio médio USD/BRL em Fevereiro 2025: 5.790124952793121\nCâmbio médio EUR/BRL em Fevereiro 2025: 5.992184221744537\nDelta Câmbio médio USD/BRL 03.2025 - 02.2024: 16.3\nDelta Câmbio médio EUR/BRL 03.2025 - 02.2024: 11.0\n"
     ]
    }
   ],
   "source": [
    "\n",
    "def get_average_rate(ticker, start_date, end_date):\n",
    "    \"\"\"\n",
    "    Baixa os dados históricos do ticker entre as datas informadas e\n",
    "    calcula a média do preço de fechamento.\n",
    "    \"\"\"\n",
    "    data = yf.download(ticker, start=start_date, end=end_date)\n",
    "    if data.empty:\n",
    "        print(f\"Nenhum dado retornado para {ticker} entre {start_date} e {end_date}\")\n",
    "        return None\n",
    "    avg_rate = data['Close'].mean()\n",
    "    return avg_rate\n",
    "\n",
    "# Tickers para as moedas:\n",
    "# Para dólar/real, o ticker utilizado é \"USDBRL=X\"\n",
    "# Para euro/real, o ticker utilizado é \"EURBRL=X\"\n",
    "ticker_usd = \"USDBRL=X\"  # Dólar em relação ao Real\n",
    "ticker_eur = \"EURBRL=X\"  # Euro em relação ao Real\n",
    "\n",
    "# Definindo os intervalos de datas\n",
    "# Marco de 2024 (de 1º de Marco até 31 de Marco, sendo o end_date 1º de Abril)\n",
    "start_mar = \"2024-03-01\"\n",
    "end_mar   = \"2024-04-01\"\n",
    "\n",
    "# Definindo os intervalos de datas\n",
    "# Novembro de 2024 (de 1º de novembro até 30 de novembro, sendo o end_date 1º de dezembro)\n",
    "start_nov = \"2024-11-01\"\n",
    "end_nov   = \"2024-12-01\"\n",
    "\n",
    "# Fevereiro de 2025 (de 1º de fevereiro até 28/29 de fevereiro, considerando end_date como 1º de março)\n",
    "start_feb = \"2025-02-01\"\n",
    "end_feb   = \"2025-03-01\"\n",
    "\n",
    "# Obtendo as médias para cada período e cada moeda - Marco.24\n",
    "usd_avg_mar = get_average_rate(ticker_usd, start_mar, end_mar)\n",
    "eur_avg_mar = get_average_rate(ticker_eur, start_mar, end_mar)\n",
    "\n",
    "# Obtendo as médias para cada período e cada moeda - Novembro.24\n",
    "usd_avg_nov = get_average_rate(ticker_usd, start_nov, end_nov)\n",
    "eur_avg_nov = get_average_rate(ticker_eur, start_nov, end_nov)\n",
    "\n",
    "# Obtendo as médias para cada período e cada moeda - Fevereiro.25\n",
    "usd_avg_feb = get_average_rate(ticker_usd, start_feb, end_feb)\n",
    "eur_avg_feb = get_average_rate(ticker_eur, start_feb, end_feb)\n",
    "\n",
    "#delta_usd_avg_feb_mar = round((usd_avg_feb/usd_avg_mar)-1,1)\n",
    "#delta_eur_avg_feb_mar = (eur_avg_mar/eur_avg_feb)* 100\n",
    "delta_usd = round(((usd_avg_feb - usd_avg_mar) / usd_avg_mar) * 100, 1)\n",
    "delta_eur = round(((eur_avg_feb - eur_avg_mar) / eur_avg_mar) * 100, 1)\n",
    "\n",
    "# Exibindo os resultados\n",
    "print(\"Câmbio médio USD/BRL em Marco 2024:\", usd_avg_mar)\n",
    "print(\"Câmbio médio EUR/BRL em Marco 2024:\", eur_avg_mar)\n",
    "print(\"Câmbio médio USD/BRL em Novembro 2024:\", usd_avg_nov)\n",
    "print(\"Câmbio médio EUR/BRL em Novembro 2024:\", eur_avg_nov)\n",
    "print(\"Câmbio médio USD/BRL em Fevereiro 2025:\", usd_avg_feb)\n",
    "print(\"Câmbio médio EUR/BRL em Fevereiro 2025:\", eur_avg_feb)\n",
    "\n",
    "# Exibindo os ganhos percentuais de marco.24 a Fevereiro.25\n",
    "print(\"Delta Câmbio médio USD/BRL 03.2025 - 02.2024:\", delta_usd)\n",
    "print(\"Delta Câmbio médio EUR/BRL 03.2025 - 02.2024:\", delta_eur)\n"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "client": "1"
   },
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "Avaliando delta cambial para aquisicao de casa - dolar x real",
   "widgets": {}
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
